### PR TITLE
FISH-10208 update to use new arquillian and configure ssl tests

### PR DESCRIPTION
**Pull request by astoica1**
- updated payara arquillian connector
- enable https option

### CODE REVIEW

**Review by simonladen — APPROVED** [review]

**Comment by Pandrex247** [comment]
Kicked off a run against all known passing TCKs, and Servlet (which hopefully this should fix), here: https://jenkins.payara.fish/job/JakartaEE-11-TCK/86/

**Comment by Pandrex247** [comment]
> Kicked off a run against all known passing TCKs, and Servlet (which hopefully this should fix), here: https://jenkins.payara.fish/job/JakartaEE-11-TCK/86/

Tests still seem to fail, though it looks like it gets further than it did before and is trying to use HTTPS
```
[ERROR]   ClientCertTests.clientCertTest:288  clientCertTest: FAILED
[ERROR]   ClientCertAnnoTests.clientCertTest:205  clientCertTest: FAILED, Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

Looks like the runner may need some extra love with setting up and configuring the key and/or trust stores

**Comment by Pandrex247** [comment]
No other TCKs have manifested new errors though, so the update to Arquillian 4.0.alpha2 hasn't had any negative consequences elsewhere.

**Review by aubi — APPROVED** [review]

**Comment by astoica1** [comment]
@Pandrex247 it seems that the import of certs is already done in the servlet tck pom: https://github.com/payara/jakartaee-10-tck-runners/blob/b84d7745e7b7278501130fa6d417f6c71b4a419d/servlet-tck/pom.xml#L139

Also I can see them being injected while Payara boots:
`[WARNING] Certificate was added to keystore
[WARNING] [Storing /payara/jakartaee-10-tck-runners/target/payara7/glassfish/domains/domain1/config/cacerts.p12]
`

**Review by Pandrex247 — APPROVED** [review]
We'll look at the failure in a follow-up issue - it does indeed seem to be adding the certificate, so we need to start looking at debugging the SSL handshake to see where it's failing

**Comment by Pandrex247** [comment]
FISH-10242 raised to track follow-up fix

**Pull request merged**
