### PR TITLE
FISH-6646 Concurrency Web Profile

### PR DESCRIPTION
**Pull request by Pandrex247**
Adds a second tck-suite.xml with the expected excluded group - activated via the `web` profile.

### CODE REVIEW

**Comment by Pandrex247** [comment]
Associated Jenkins PR: https://github.com/payara/jenkinsjobs/pull/137

**Review by breakponchito — APPROVED** [review]
LGTM

**Review by aubi — APPROVED** [review]
LGTM
Thank you for the moving Concurrent doc from root to the directory, I always forgot.

**Comment by Pandrex247** [comment]
Doesn't seem to be working on Jenkins...

**Comment by Pandrex247** [comment]
Passing now

**Pull request merged**
