### PR TITLE
FISH-6342 Add Dependency Injection TCK

### PR DESCRIPTION
**Pull request by kalinchan**
Running org.jboss.weld.atinject.tck.AtInjectTCK
Jun 08, 2022 11:15:21 AM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 5.0.0 (SP1)
Jun 08, 2022 11:15:22 AM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Tests run: 50, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.573 sec

Results :

Tests run: 50, Failures: 0, Errors: 0, Skipped: 0

cc @aubi  @Pandrex247

### CODE REVIEW

**Comment by Pandrex247** [comment]
Is this the right way of doing this? Just pulling in and compiling the TCK?
With our existing porting package we don't do that https://github.com/payara/ditck-porting/tree/5140eaf7747855df95a825c15c14eb6481cc63b4

**Comment by Pandrex247** [comment]
Or are these classes something else?

**Comment by kalinchan** [comment]
I believe that the porting package reuses [Weld's Inject Porting package](https://github.com/weld/core/tree/master/inject-tck-runner/src/test/java/org/jboss/weld/atinject/tck) this is just the simpler approach.

The same amount of tests are running and this is also how Wildfly did it

**Review by Pandrex247 — COMMENTED** [review]
I might be wrong, but I'm not convinced this is actually running against Payara? I think this is just running against standalone Weld

**Comment by kalinchan** [comment]
I believe that is expected, if you look at the [previous TCK run](https://jenkins.payara.fish/blue/organizations/jenkins/TCK-Suite/detail/TCK-Suite/384/pipeline/99), it doesn't run against Payara

**Pull request closed without merging**
